apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  namespace: microservices-app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: stories.com
      http:
        paths:
          # CREATE Story
          - path: ^/stories/create$
            pathType: ImplementationSpecific
            backend:
              service:
                name: stories-clusterip-srv
                port:
                  number: 4006

          # GET Stories (Query Service)
          - path: ^/stories/?$
            pathType: ImplementationSpecific
            backend:
              service:
                name: query-srv
                port:
                  number: 4008

          # Story Comments (Regex route)
          - path: ^/stories/.*/comments$
            pathType: ImplementationSpecific
            backend:
              service:
                name: comments-srv
                port:
                  number: 4007

          # Client frontend (default)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 80
